name: CI

on: [push, pull_request]

jobs:
  winbuild:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml.5.0.0,ocaml-option-mingw
          opam-local-packages: bechamel.opam
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2

      - run: opam pin add . -n
      - run: opam install bechamel --with-test -v

  winbuild4:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml.4.14.0,ocaml-option-mingw
          opam-local-packages: bechamel.opam
          opam-repositories: |
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2

      - run: opam pin add . -n
      - run: opam install bechamel --with-test -v
